# api
# base properties
API_BASE_URL=https://reqres.in/api
API_EMAIL=eve.holt@reqres.in

# api
# mock
API_MOCK_BASE_URL=http://localhost:8000

# ui
OPTION_BROWSER=Chrome
OPTION_HEADLESS=false
OPTION_BASE_URI=https://www.wikipedia.org
OPTION_RU_BASE_URI=https://ru.wikipedia.org
OPTION_BROWSER_SIZE=2560x1440